version: '3.8'

services:
  redis:
    image: redis:8.6.2 # https://hub.docker.com/_/redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Web-UI for Redis: https://redis.io/insight/
  # Überblick weitere Redis-UIs: https://uibakery.io/blog/redis-gui-tools
  redisinsight:
    image: redis/redisinsight:3.4 # https://hub.docker.com/r/redislabs/redisinsight
    container_name: redisinsight-produktdatenbank
    ports:
      - "5540:5540"